ALTER TABLE "PanelButtons"
ALTER
COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Update existing tables to use bigint[] instead of numeric(20,0)[]
ALTER TABLE "PanelButtons"
ALTER
COLUMN "SupportRoles" TYPE bigint[],
    ALTER
COLUMN "ViewerRoles" TYPE bigint[];

ALTER TABLE "SelectMenuOptions"
ALTER
COLUMN "SupportRoles" TYPE bigint[],
    ALTER
COLUMN "ViewerRoles" TYPE bigint[];

-- Also update other Discord ID columns to bigint for consistency
ALTER TABLE "TicketPanels"
ALTER
COLUMN "GuildId" TYPE bigint,
    ALTER
COLUMN "ChannelId" TYPE bigint,
    ALTER
COLUMN "MessageId" TYPE bigint;

ALTER TABLE "PanelButtons"
ALTER
COLUMN "CategoryId" TYPE bigint,
    ALTER
COLUMN "ArchiveCategoryId" TYPE bigint;

ALTER TABLE "SelectMenuOptions"
ALTER
COLUMN "CategoryId" TYPE bigint,
    ALTER
COLUMN "ArchiveCategoryId" TYPE bigint;

ALTER TABLE "Tickets"
ALTER
COLUMN "GuildId" TYPE bigint,
    ALTER
COLUMN "ChannelId" TYPE bigint,
    ALTER
COLUMN "CreatorId" TYPE bigint,
    ALTER
COLUMN "ClaimedBy" TYPE bigint;

ALTER TABLE "TicketCases"
ALTER
COLUMN "GuildId" TYPE bigint,
    ALTER
COLUMN "CreatedBy" TYPE bigint;

ALTER TABLE "CaseNotes"
ALTER
COLUMN "AuthorId" TYPE bigint;

ALTER TABLE "NoteEdits"
ALTER
COLUMN "EditorId" TYPE bigint;

ALTER TABLE "TicketNotes"
ALTER
COLUMN "AuthorId" TYPE bigint;

ALTER TABLE "PanelButtons"
    ADD COLUMN IF NOT EXISTS "DeleteOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add enhanced close/archive behavior columns to SelectMenuOptions
ALTER TABLE "SelectMenuOptions"
    ADD COLUMN IF NOT EXISTS "DeleteOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add guild-wide default settings to GuildTicketSettings
ALTER TABLE "GuildTicketSettings"
    ADD COLUMN IF NOT EXISTS "DeleteTicketsOnClose" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "LockTicketsOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameTicketsOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnClose" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "DeleteDelay" INTERVAL NOT NULL DEFAULT INTERVAL '5 minutes',
    ADD COLUMN IF NOT EXISTS "LockTicketsOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RenameTicketsOnArchive" BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS "RemoveCreatorOnArchive" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AutoArchiveOnClose" BOOLEAN NOT NULL DEFAULT FALSE;

-- Add deletion tracking to Tickets table
ALTER TABLE "Tickets"
    ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE;

-- Create index for finding non-deleted tickets (performance optimization)
CREATE INDEX IF NOT EXISTS "IX_Tickets_IsDeleted_GuildId"
    ON "Tickets" ("IsDeleted", "GuildId")
    WHERE "IsDeleted" = FALSE;

-- Create index for auto-close queries (performance optimization)
CREATE INDEX IF NOT EXISTS "IX_Tickets_AutoClose_Lookup"
    ON "Tickets" ("IsArchived", "ClosedAt", "LastActivityAt")
    WHERE "IsArchived" = FALSE AND "ClosedAt" IS NULL;
