// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("GuildAiProviderLinks")]
	public class GuildAiProviderLink
	{
		[Column("Id"          , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id           { get; set; } // integer
		[Column("GuildId"                                                                                             )] public ulong     GuildId      { get; set; } // numeric(20,0)
		[Column("Provider"                                                                                            )] public int       Provider     { get; set; } // integer
		[Column("ApiKey"      , CanBeNull    = false                                                                   )] public string    ApiKey       { get; set; } = null!; // text
		[Column("DefaultModel"                                                                                        )] public string?   DefaultModel { get; set; } // text
		[Column("IsEnabled"                                                                                           )] public bool      IsEnabled    { get; set; } // boolean
		[Column("IsDefault"                                                                                           )] public bool      IsDefault    { get; set; } // boolean
		[Column("DateAdded"                                                                                           )] public DateTime? DateAdded    { get; set; } // timestamp (6) without time zone
		[Column("DateUpdated"                                                                                         )] public DateTime? DateUpdated  { get; set; } // timestamp (6) without time zone
	}
}
