// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("MusicPlayerSettings")]
	public class MusicPlayerSetting
	{
		[Column("Id"               , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id                { get; set; } // integer
		[Column("GuildId"                                                                                            )] public ulong  GuildId           { get; set; } // numeric(20,0)
		[Column("PlayerRepeat"                                                                                       )] public int      PlayerRepeat      { get; set; } // integer
		[Column("MusicChannelId"                                                                                     )] public ulong? MusicChannelId    { get; set; } // numeric(20,0)
		[Column("Volume"                                                                                             )] public int      Volume            { get; set; } // integer
		[Column("AutoDisconnect"                                                                                     )] public int      AutoDisconnect    { get; set; } // integer
		[Column("AutoPlay"                                                                                           )] public int      AutoPlay          { get; set; } // integer
		[Column("DjRoleId"                                                                                           )] public ulong? DjRoleId          { get; set; } // numeric(20,0)
		[Column("VoteSkipEnabled"                                                                                    )] public bool     VoteSkipEnabled   { get; set; } // boolean
		[Column("VoteSkipThreshold"                                                                                  )] public int      VoteSkipThreshold { get; set; } // integer
	}
}
