// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("PanelButtons")]
	public class PanelButton
	{
		[Column("Id"                  , IsPrimaryKey = true )] public int        Id                   { get; set; } // integer
		[Column("PanelId"                                   )] public int        PanelId              { get; set; } // integer
		[Column("Label"               , CanBeNull    = false)] public string     Label                { get; set; } = null!; // text
		[Column("Emoji"                                     )] public string?    Emoji                { get; set; } // text
		[Column("CustomId"            , CanBeNull    = false)] public string     CustomId             { get; set; } = null!; // text
		[Column("Style"                                     )] public int        Style                { get; set; } // integer
		[Column("OpenMessageJson"                           )] public string?    OpenMessageJson      { get; set; } // text
		[Column("ModalJson"                                 )] public string?    ModalJson            { get; set; } // text
		[Column("ChannelNameFormat"   , CanBeNull    = false)] public string     ChannelNameFormat    { get; set; } = null!; // text
		[Column("CategoryId"                                )] public ulong?   CategoryId           { get; set; } // numeric(20,0)
		[Column("ArchiveCategoryId"                         )] public ulong?   ArchiveCategoryId    { get; set; } // numeric(20,0)
		[Column("SupportRoles"                              )] public ulong[]? SupportRoles         { get; set; } // numeric(20,0)[]
		[Column("ViewerRoles"                               )] public ulong[]? ViewerRoles          { get; set; } // numeric(20,0)[]
		[Column("AutoCloseTime"                             )] public TimeSpan?  AutoCloseTime        { get; set; } // interval
		[Column("RequiredResponseTime"                      )] public TimeSpan?  RequiredResponseTime { get; set; } // interval
		[Column("MaxActiveTickets"                          )] public int        MaxActiveTickets     { get; set; } // integer
		[Column("AllowedPriorities"                         )] public string[]?  AllowedPriorities    { get; set; } // text[]
		[Column("DefaultPriority"                           )] public string?    DefaultPriority      { get; set; } // text
		[Column("SaveTranscript"                            )] public bool       SaveTranscript       { get; set; } // boolean

		#region Associations
		/// <summary>
		/// FK_PanelButtons_TicketPanels_Id
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(Id), OtherKey = nameof(TicketPanel.Id))]
		public TicketPanel TicketPanelsId { get; set; } = null!;

		/// <summary>
		/// FK_PanelButtons_TicketPanels_PanelId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(PanelId), OtherKey = nameof(TicketPanel.Id))]
		public TicketPanel Panel { get; set; } = null!;

		/// <summary>
		/// FK_Tickets_PanelButtons_ButtonId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Ticket.ButtonId))]
		public IEnumerable<Ticket> Tickets { get; set; } = null!;
		#endregion
	}
}
