// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Poll")]
	public class Poll
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("GuildId"                                                                                    )] public ulong   GuildId   { get; set; } // numeric(20,0)
		[Column("ChannelId"                                                                                  )] public ulong   ChannelId { get; set; } // numeric(20,0)
		[Column("Question"                                                                                   )] public string?   Question  { get; set; } // text
		[Column("PollType"                                                                                   )] public int       PollType  { get; set; } // integer
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_PollAnswer_Poll_PollsId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(PollAnswer.PollsId))]
		public IEnumerable<PollAnswer> PollAnswers { get; set; } = null!;

		/// <summary>
		/// FK_PollVote_Poll_PollsId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(PollVote.PollsId))]
		public IEnumerable<PollVote>? PollVotes { get; set; } = null!;
		#endregion
	}
}
