// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("PollVote")]
	public class PollVote
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("UserId"                                                                                     )] public ulong   UserId    { get; set; } // numeric(20,0)
		[Column("VoteIndex"                                                                                  )] public int       VoteIndex { get; set; } // integer
		[Column("PollId"                                                                                     )] public int       PollId    { get; set; } // integer
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone
		[Column("PollsId"                                                                                    )] public int?      PollsId   { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_PollVote_Poll_PollsId
		/// </summary>
		[Association(ThisKey = nameof(PollsId), OtherKey = nameof(Poll.Id))]
		public Poll? Polls { get; set; }
		#endregion
	}
}
