// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("PollAnswer")]
	public class PollAnswer
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id        { get; set; } // integer
		[Column("Text"                                                                                       )] public string?   Text      { get; set; } // text
		[Column("Index"                                                                                      )] public int       Index     { get; set; } // integer
		[Column("PollsId"                                                                                    )] public int?      PollsId   { get; set; } // integer
		[Column("DateAdded"                                                                                  )] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone

		#region Associations
		/// <summary>
		/// FK_PollAnswer_Poll_PollsId
		/// </summary>
		[Association(ThisKey = nameof(PollsId), OtherKey = nameof(Poll.Id))]
		public Poll? Polls { get; set; }
		#endregion
	}
}
