// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("UserXpStats")]
	public class UserXpStat
	{
		[Column("Id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id              { get; set; } // integer
		[Column("UserId"                                                                                           )] public ulong   UserId          { get; set; } // numeric(20,0)
		[Column("GuildId"                                                                                          )] public ulong   GuildId         { get; set; } // numeric(20,0)
		[Column("Xp"                                                                                               )] public int       Xp              { get; set; } // integer
		[Column("AwardedXp"                                                                                        )] public int       AwardedXp       { get; set; } // integer
		[Column("NotifyOnLevelUp"                                                                                  )] public int       NotifyOnLevelUp { get; set; } // integer
		[Column("LastLevelUp"                                                                                      )] public DateTime  LastLevelUp     { get; set; } // timestamp (6) without time zone
		[Column("DateAdded"                                                                                        )] public DateTime? DateAdded       { get; set; } // timestamp (6) without time zone
	}
}
