name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/Mewdeko/Mewdeko.csproj

    - name: Build
      run: dotnet publish src/Mewdeko/Mewdeko.csproj --no-restore -c Release -r win-x86 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:UseAppHost=true -o output/

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Zip artifacts
      run: |
        cd output
        Compress-Archive -Path * -DestinationPath ../Mewdeko.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Mewdeko
        path: Mewdeko.zip
